<?php require 'header.php';
$a=$activity?: (object)array(); $items=is_array($schedule_items??null)?$schedule_items:array(); $attachments=is_array($attachments??null)?$attachments:array();
function activityFormH($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$typeLabels=array('work_schedule'=>'Lịch công tác','training_plan'=>'Kế hoạch đào tạo, tập huấn','medical_campaign'=>'Chiến dịch truyền thông và khám nhân đạo');
$typeRoutes=array('work_schedule'=>'schedules','training_plan'=>'plans','medical_campaign'=>'campaigns');
$selectedType=$a->activity_type??($activity_scope_type??'work_schedule');
$backRoute=$typeRoutes[$selectedType]??'schedules';
$isSchedule=$selectedType==='work_schedule';
?>
<script src="https://cdn.ckeditor.com/ckeditor5/40.0.0/super-build/ckeditor.js"></script>
<style>.schedule-row{background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:12px;margin-bottom:10px}.attachment-chip{display:inline-flex;gap:7px;align-items:center;padding:7px 10px;border:1px solid #e2e8f0;border-radius:9px;margin:3px}@media(max-width:767px){.schedule-row .col-md-2,.schedule-row .col-md-3,.schedule-row .col-md-4{margin-bottom:8px}}</style>
<div class="content container-fluid"><div class="page-header"><div class="row align-items-center"><div class="col"><h3 class="page-title"><?php echo $method==='edit'?'Chỉnh sửa ':'Khởi tạo ';?><?php echo activityFormH(mb_strtolower($typeLabels[$selectedType]??'hoạt động','UTF-8'));?></h3></div><div class="col-auto"><a class="btn btn-outline-secondary" href="<?php echo XC_URL.'/admin/activities/'.$backRoute;?>">Quay lại</a></div></div></div>
<form id="activity-form" enctype="multipart/form-data"><input type="hidden" name="id" value="<?php echo intval($a->id??0);?>"><input type="hidden" name="csrf_token" value="<?php echo activityFormH($admin_csrf_token??'');?>">
<div class="card"><div class="card-body"><div class="row g-3">
 <input type="hidden" id="activity_type" name="activity_type" value="<?php echo activityFormH($selectedType);?>">
 <?php if($isSchedule):?>
 <div class="col-md-6"><label class="form-label">Tuần làm việc <span class="text-danger">*</span></label><input class="form-control" type="text" name="work_week" value="<?php echo activityFormH($a->work_week??'');?>" placeholder="Ví dụ: Tuần 41 (05/10/2026 - 11/10/2026)" required maxlength="100"></div>
 <div class="col-md-6"><label class="form-label">Khối <span class="text-danger">*</span></label><select class="form-select" name="organization_block" required><option value="">-- Chọn khối --</option><option value="leadership" <?php echo ($a->organization_block??'')==='leadership'?'selected':'';?>>Ban lãnh đạo</option><option value="departments" <?php echo ($a->organization_block??'')==='departments'?'selected':'';?>>Các khoa phòng</option></select></div>
 <div class="col-12"><label class="form-label">Tiêu đề <span class="text-danger">*</span></label><input class="form-control" type="text" name="title" value="<?php echo activityFormH($a->title??'');?>" required maxlength="255" placeholder="Nhập tiêu đề lịch công tác"></div>
 <div class="col-12"><label class="form-label">Nội dung chi tiết</label><textarea class="form-control" id="activity_content" rows="12" name="content"><?php echo activityFormH($a->content??'');?></textarea></div>
 <div class="col-12"><label class="form-label">Tải file</label><input class="form-control" type="file" name="attachments[]" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx"><small class="text-muted">Hỗ trợ PDF, Word, Excel, PowerPoint; tối đa 20MB mỗi file.</small></div>
 <?php else:?>
 <div class="col-md-4"><label class="form-label">Phân hệ</label><input class="form-control" value="<?php echo activityFormH($typeLabels[$selectedType]??'Hoạt động');?>" readonly></div>
 <div class="col-md-8"><label class="form-label">Tiêu đề *</label><input class="form-control" name="title" value="<?php echo activityFormH($a->title??'');?>" required maxlength="255"></div>
 <div class="col-md-6"><label class="form-label">Đơn vị phụ trách</label><input class="form-control" name="department_name" value="<?php echo activityFormH($a->department_name??'');?>"></div><div class="col-md-6"><label class="form-label">Địa điểm</label><input class="form-control" name="location" value="<?php echo activityFormH($a->location??'');?>"></div>
 <div class="col-md-3"><label class="form-label">Bắt đầu</label><input type="datetime-local" class="form-control" name="start_at" value="<?php echo !empty($a->start_at)?date('Y-m-d\TH:i',strtotime($a->start_at)):'';?>"></div><div class="col-md-3"><label class="form-label">Kết thúc</label><input type="datetime-local" class="form-control" name="end_at" value="<?php echo !empty($a->end_at)?date('Y-m-d\TH:i',strtotime($a->end_at)):'';?>"></div>
 <div class="col-md-3"><label class="form-label">Ảnh đại diện</label><input class="form-control" type="file" name="thumbnail" accept="image/jpeg,image/png,image/webp"></div><div class="col-md-3"><label class="form-label">Tài liệu đính kèm</label><input class="form-control" type="file" name="attachments[]" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx"></div>
 <div class="col-12"><label class="form-label">Mô tả ngắn</label><textarea class="form-control" rows="3" name="summary"><?php echo activityFormH($a->summary??'');?></textarea></div>
 <div class="col-12"><label class="form-label">Nội dung chi tiết</label><textarea class="form-control" id="activity_content" rows="10" name="content"><?php echo activityFormH($a->content??'');?></textarea></div>
 <div class="col-md-8"><label class="form-label">Thông tin liên hệ/đăng ký</label><textarea class="form-control" rows="2" name="contact_info"><?php echo activityFormH($a->contact_info??'');?></textarea></div><div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="is_featured" id="featured" <?php echo !empty($a->is_featured)?'checked':'';?>><label class="form-check-label" for="featured">Hoạt động nổi bật</label></div></div>
 <?php endif;?>
 <?php if($attachments):?><div class="col-12"><label class="form-label d-block">Tệp đã tải</label><?php foreach($attachments as $f):?><span class="attachment-chip"><i class="fa-solid fa-paperclip"></i><a target="_blank" href="<?php echo XC_URL.'/uploads/activities/'.rawurlencode($f->file_path);?>"><?php echo activityFormH($f->file_name);?></a><label class="text-danger mb-0"><input type="checkbox" name="delete_attachment[]" value="<?php echo intval($f->id);?>"> Xóa</label></span><?php endforeach;?></div><?php endif;?>
</div></div></div>
<div class="text-end mb-4"><a class="btn btn-light" href="<?php echo XC_URL.'/admin/activities/'.$backRoute;?>">Hủy</a><button class="btn btn-primary px-4" id="save-activity"><i class="fa-solid fa-floppy-disk me-1"></i>Lưu bản nháp</button></div></form></div>
<script>
$(function(){var editor=null;if(window.CKEDITOR){CKEDITOR.ClassicEditor.create(document.querySelector('#activity_content'),{toolbar:{items:['heading','|','bold','italic','link','bulletedList','numberedList','|','insertTable','blockQuote','undo','redo']},removePlugins:['CKBox','CKFinder','EasyImage','RealTimeCollaborativeComments','RealTimeCollaborativeTrackChanges','RealTimeCollaborativeRevisionHistory','PresenceList','Comments','TrackChanges','RevisionHistory','Pagination','WProofreader','MathType','SlashCommand','Template','DocumentOutline','FormatPainter','TableOfContents']}).then(function(e){editor=e}).catch(function(){})}
$('#activity-form').submit(function(e){e.preventDefault();var fd=new FormData(this);if(editor)fd.set('content',editor.getData());$('#save-activity').prop('disabled',true);$.ajax({url:'<?php echo XC_URL;?>/api/activitySave',type:'POST',data:fd,processData:false,contentType:false,dataType:'json'}).done(function(r){if(r.status==200){Swal.fire({icon:'success',title:r.message,timer:1200,showConfirmButton:false});setTimeout(function(){location.href=r.returnUrl},1250)}else Swal.fire('Không thể lưu',r.message,'error')}).fail(function(){Swal.fire('Lỗi','Không thể kết nối máy chủ.','error')}).always(function(){$('#save-activity').prop('disabled',false)})});});
</script>
<?php require 'footer.php';?>
