<?php require 'header.php';
$a=$activity;$items=is_array($schedule_items??null)?$schedule_items:array();$attachments=is_array($attachments??null)?$attachments:array();$logs=is_array($workflow_logs??null)?$workflow_logs:array();
$labels=array('work_schedule'=>'Lịch công tác','training_plan'=>'Đào tạo & tập huấn','medical_campaign'=>'Truyền thông & khám nhân đạo');$statuses=array(1=>'Bản nháp',2=>'Chờ phê duyệt',3=>'Đã phê duyệt',4=>'Đã công khai');
$typeRoutes=array('work_schedule'=>'schedules','training_plan'=>'plans','medical_campaign'=>'campaigns');$backRoute=$typeRoutes[$a->activity_type]??'schedules';
function activityDetailH($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<div class="content container-fluid"><div class="page-header"><div class="row align-items-center"><div class="col"><h3 class="page-title">Chi tiết <?php echo activityDetailH(mb_strtolower($labels[$a->activity_type]??'hoạt động','UTF-8'));?></h3></div><div class="col-auto"><a class="btn btn-outline-secondary" href="<?php echo XC_URL.'/admin/activities/'.$backRoute;?>">Quay lại</a> <a class="btn btn-outline-primary" target="_blank" href="<?php echo XC_URL.'/hoat-dong/lich-cong-tac.html?activity='.intval($a->id).'#lich-cong-tac';?>"><i class="fa-solid fa-arrow-up-right-from-square me-1"></i>Xem frontend</a><?php if(intval($a->status)===1&&intval($a->created_by)===intval($_SESSION['user']['id']??0)):?> <a class="btn btn-primary" href="<?php echo XC_URL.'/admin/activities/edit/'.intval($a->id);?>">Chỉnh sửa</a><?php endif;?></div></div></div>
<div class="row"><div class="col-lg-8"><div class="card"><div class="card-body"><div class="d-flex gap-2 mb-3"><span class="badge bg-primary"><?php echo $labels[$a->activity_type]??'';?></span><span class="badge bg-secondary"><?php echo $statuses[intval($a->status)]??'';?></span></div><h3><?php echo activityDetailH($a->title);?></h3><p class="text-muted"><?php echo nl2br(activityDetailH($a->summary));?></p><hr><div class="activity-detail-content"><?php echo $a->content;?></div></div></div>
<?php if($items):?><div class="card"><div class="card-header"><h5 class="mb-0">Chi tiết lịch công tác</h5></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Ngày/giờ</th><th>Nội dung</th><th>Chủ trì</th><th>Địa điểm</th><th>Thành phần</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><?php echo date('d/m/Y',strtotime($i->work_date));?><br><small><?php echo activityDetailH(substr($i->start_time??'',0,5));?> - <?php echo activityDetailH(substr($i->end_time??'',0,5));?></small></td><td><?php echo activityDetailH($i->work_content);?></td><td><?php echo activityDetailH($i->chairperson);?></td><td><?php echo activityDetailH($i->location);?></td><td><?php echo activityDetailH($i->participants);?></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?></div>
<div class="col-lg-4"><div class="card"><div class="card-header"><h5 class="mb-0">Thông tin</h5></div><div class="card-body"><?php if($a->activity_type==='work_schedule'):?><p><b>Tuần làm việc:</b><br><?php echo activityDetailH($a->work_week);?></p><p><b>Khối:</b><br><?php echo ($a->organization_block??'')==='leadership'?'Ban lãnh đạo':((($a->organization_block??'')==='departments')?'Các khoa phòng':'—');?></p><?php else:?><p><b>Đơn vị:</b><br><?php echo activityDetailH($a->department_name);?></p><p><b>Địa điểm:</b><br><?php echo activityDetailH($a->location);?></p><p><b>Thời gian:</b><br><?php echo $a->start_at?date('d/m/Y H:i',strtotime($a->start_at)):'—';?></p><?php endif;?><p><b>Người tạo:</b><br><?php echo activityDetailH($a->author_name);?></p><?php if($a->rejection_reason):?><div class="alert alert-warning"><b>Lý do trả lại:</b><br><?php echo activityDetailH($a->rejection_reason);?></div><?php endif;?></div></div>
<?php if($attachments):?><div class="card"><div class="card-header"><h5 class="mb-0">Tài liệu</h5></div><div class="list-group list-group-flush"><?php foreach($attachments as $f):?><a target="_blank" class="list-group-item list-group-item-action" href="<?php echo XC_URL.'/uploads/activities/'.rawurlencode($f->file_path);?>"><i class="fa-solid fa-paperclip me-2"></i><?php echo activityDetailH($f->file_name);?></a><?php endforeach;?></div></div><?php endif;?>
<div class="card"><div class="card-header"><h5 class="mb-0">Lịch sử xử lý</h5></div><div class="card-body"><div class="timeline"><?php foreach($logs as $l):?><div class="border-start ps-3 pb-3"><b><?php echo activityDetailH($l->action);?></b><br><small><?php echo activityDetailH($l->actor_name);?> · <?php echo date('d/m/Y H:i',strtotime($l->acted_at));?></small><?php if($l->note):?><div><?php echo activityDetailH($l->note);?></div><?php endif;?></div><?php endforeach;?></div></div></div></div></div></div>
<?php require 'footer.php';?>
