<?php require 'header.php';$c=$medical_campaign?: (object)array();function campaignFormH($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}?>
<script src="https://cdn.ckeditor.com/ckeditor5/40.0.0/super-build/ckeditor.js"></script>
<div class="content container-fluid"><div class="page-header"><div class="row align-items-center"><div class="col"><h3 class="page-title"><?php echo $method==='edit'?'Chỉnh sửa':'Thêm';?> chiến dịch y tế</h3></div><div class="col-auto"><a class="btn btn-outline-secondary" href="<?php echo XC_URL;?>/admin/campaigns">Quay lại</a></div></div></div>
<form id="campaign-form" enctype="multipart/form-data"><input type="hidden" name="id" value="<?php echo intval($c->id??0);?>"><input type="hidden" name="csrf_token" value="<?php echo campaignFormH($admin_csrf_token??'');?>"><div class="card"><div class="card-body"><div class="row g-3">
<div class="col-md-3"><label class="form-label">Mã chiến dịch <span class="text-danger">*</span></label><input class="form-control" name="campaign_code" required maxlength="50" value="<?php echo campaignFormH($c->campaign_code??'');?>" placeholder="CD-2026-001"></div>
<div class="col-md-4"><label class="form-label">Loại chiến dịch <span class="text-danger">*</span></label><select class="form-select" name="campaign_type" required><option value="truyenthong" <?php echo ($c->campaign_type??'')==='truyenthong'?'selected':'';?>>Chiến dịch truyền thông</option><option value="nhandao" <?php echo ($c->campaign_type??'')==='nhandao'?'selected':'';?>>Khám chữa bệnh nhân đạo</option></select></div>
<div class="col-md-5"><label class="form-label">Đơn vị tổ chức</label><input class="form-control" name="organizer" value="<?php echo campaignFormH($c->organizer??'');?>"></div>
<div class="col-12"><label class="form-label">Tên chiến dịch <span class="text-danger">*</span></label><input class="form-control" name="title" required maxlength="500" value="<?php echo campaignFormH($c->title??'');?>"></div>
<div class="col-12"><label class="form-label">Mô tả chiến dịch</label><textarea class="form-control" rows="4" name="summary"><?php echo campaignFormH($c->summary??'');?></textarea></div>
<div class="col-12"><label class="form-label">Mô tả chi tiết</label><textarea class="form-control" id="campaign_content" rows="12" name="content"><?php echo campaignFormH($c->content??'');?></textarea></div>
<div class="col-md-3"><label class="form-label">Từ ngày <span class="text-danger">*</span></label><input type="date" class="form-control" name="start_date" required value="<?php echo campaignFormH($c->start_date??'');?>"></div><div class="col-md-3"><label class="form-label">Đến ngày <span class="text-danger">*</span></label><input type="date" class="form-control" name="end_date" required value="<?php echo campaignFormH($c->end_date??'');?>"></div>
<div class="col-md-6"><label class="form-label">Địa điểm <span class="text-danger">*</span></label><input class="form-control" name="location" required value="<?php echo campaignFormH($c->location??'');?>"></div>
<div class="col-md-8"><label class="form-label">Đối tượng thụ hưởng/tham gia</label><textarea class="form-control" rows="2" name="target_audience"><?php echo campaignFormH($c->target_audience??'');?></textarea></div><div class="col-md-4"><label class="form-label">Thứ tự hiển thị</label><input type="number" class="form-control" name="sort_order" value="<?php echo intval($c->sort_order??0);?>"></div>
<div class="col-md-6"><label class="form-label">Ảnh đại diện <?php echo empty($c->image_path)?'<span class="text-danger">*</span>':'';?></label><input class="form-control" type="file" name="image" accept="image/jpeg,image/png,image/webp" <?php echo empty($c->image_path)?'required':'';?>><small class="text-muted">JPG, PNG hoặc WEBP; tối đa 5MB.</small><?php if(!empty($c->image_path)):?><img class="mt-2 rounded" style="width:180px;height:100px;object-fit:cover" src="<?php echo XC_URL.'/uploads/medical-campaigns/'.rawurlencode($c->image_path);?>" alt=""><?php endif;?></div>
<div class="col-md-6"><label class="form-label">Tệp kế hoạch PDF <?php echo empty($c->attachment_path)?'<span class="text-danger">*</span>':'';?></label><input class="form-control" type="file" name="attachment" accept="application/pdf,.pdf" <?php echo empty($c->attachment_path)?'required':'';?>><small class="text-muted">PDF tối đa 20MB.</small><?php if(!empty($c->attachment_path)):?><div class="mt-2"><a target="_blank" href="<?php echo XC_URL.'/uploads/medical-campaigns/'.rawurlencode($c->attachment_path);?>"><i class="fa-regular fa-file-pdf me-1"></i><?php echo campaignFormH($c->attachment_name);?></a></div><?php endif;?></div>
</div></div></div><div class="text-end mb-4"><a class="btn btn-light" href="<?php echo XC_URL;?>/admin/campaigns">Hủy</a> <button class="btn btn-primary" id="save-campaign"><i class="fa-solid fa-floppy-disk me-1"></i>Lưu bản nháp</button></div></form></div>
<script>$(function(){var editor=null;if(window.CKEDITOR){CKEDITOR.ClassicEditor.create(document.querySelector('#campaign_content'),{toolbar:{items:['heading','|','bold','italic','underline','link','bulletedList','numberedList','|','insertTable','blockQuote','undo','redo']},removePlugins:['CKBox','CKFinder','EasyImage','RealTimeCollaborativeComments','RealTimeCollaborativeTrackChanges','RealTimeCollaborativeRevisionHistory','PresenceList','Comments','TrackChanges','RevisionHistory','Pagination','WProofreader','MathType','SlashCommand','Template','DocumentOutline','FormatPainter','TableOfContents']}).then(function(e){editor=e}).catch(function(){})}$('#campaign-form').submit(function(e){e.preventDefault();var fd=new FormData(this),btn=$('#save-campaign').prop('disabled',true);if(editor)fd.set('content',editor.getData());$.ajax({url:'<?php echo XC_URL;?>/api/medicalCampaignSave',type:'POST',data:fd,processData:false,contentType:false,dataType:'json'}).done(function(r){if(r.status==200){Swal.fire({icon:'success',title:r.message,timer:1000,showConfirmButton:false});setTimeout(function(){location.href=r.returnUrl},1050)}else Swal.fire('Không thể lưu',r.message,'error')}).fail(function(){Swal.fire('Lỗi','Không thể kết nối máy chủ.','error')}).always(function(){btn.prop('disabled',false)})})});</script>
<?php require 'footer.php';?>
