<?php require 'header.php';$p=$training_plan?: (object)array();function trainingFormH($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}?>
<div class="content container-fluid">
 <div class="page-header"><div class="row align-items-center"><div class="col"><h3 class="page-title"><?php echo $method==='edit'?'Chỉnh sửa':'Thêm';?> kế hoạch đào tạo, tập huấn</h3></div><div class="col-auto"><a class="btn btn-outline-secondary" href="<?php echo XC_URL;?>/admin/trainings">Quay lại</a></div></div></div>
 <form id="training-plan-form" enctype="multipart/form-data"><input type="hidden" name="id" value="<?php echo intval($p->id??0);?>"><input type="hidden" name="csrf_token" value="<?php echo trainingFormH($admin_csrf_token??'');?>">
  <div class="card"><div class="card-body"><div class="row g-3">
   <div class="col-md-3"><label class="form-label">Mã kế hoạch <span class="text-danger">*</span></label><input class="form-control" name="plan_code" required maxlength="50" value="<?php echo trainingFormH($p->plan_code??'');?>" placeholder="DT-2026-001"></div>
   <div class="col-md-6"><label class="form-label">Tên đào tạo & tập huấn <span class="text-danger">*</span></label><input class="form-control" name="title" required maxlength="500" value="<?php echo trainingFormH($p->title??'');?>"></div>
   <div class="col-md-3"><label class="form-label">Mức độ ưu tiên</label><select class="form-select" name="priority_level"><?php foreach(array('normal'=>'Thông thường','focus'=>'Trọng tâm','urgent'=>'Bắt buộc/Khẩn') as $v=>$l):?><option value="<?php echo $v;?>" <?php echo ($p->priority_level??'normal')===$v?'selected':'';?>><?php echo $l;?></option><?php endforeach;?></select></div>
   <div class="col-12"><label class="form-label">Mô tả ngắn</label><textarea class="form-control" rows="3" name="summary"><?php echo trainingFormH($p->summary??'');?></textarea></div>
   <div class="col-md-3"><label class="form-label">Từ ngày <span class="text-danger">*</span></label><input type="date" class="form-control" name="start_date" required value="<?php echo trainingFormH($p->start_date??'');?>"></div>
   <div class="col-md-3"><label class="form-label">Đến ngày <span class="text-danger">*</span></label><input type="date" class="form-control" name="end_date" required value="<?php echo trainingFormH($p->end_date??'');?>"></div>
   <div class="col-md-6"><label class="form-label">Đơn vị tổ chức <span class="text-danger">*</span></label><input class="form-control" name="organizer" required value="<?php echo trainingFormH($p->organizer??'');?>"></div>
   <div class="col-md-6"><label class="form-label">Đối tượng tham gia</label><textarea class="form-control" rows="2" name="target_staff"><?php echo trainingFormH($p->target_staff??'');?></textarea></div>
   <div class="col-md-6"><label class="form-label">Khoa/phòng chủ trì</label><input class="form-control" name="department_name" value="<?php echo trainingFormH($p->department_name??'');?>"></div>
   <div class="col-md-4"><label class="form-label">Hình thức đào tạo</label><select class="form-select" name="training_form"><?php foreach(array('tap-trung'=>'Tập trung trực tiếp','truc-tuyen'=>'Trực tuyến / E-learning','ket-hop'=>'Kết hợp (Hybrid)') as $v=>$l):?><option value="<?php echo $v;?>" <?php echo ($p->training_form??'tap-trung')===$v?'selected':'';?>><?php echo $l;?></option><?php endforeach;?></select></div>
   <div class="col-md-4"><label class="form-label">Cấp chứng chỉ</label><select class="form-select" name="certificate_type"><option value="cme" <?php echo ($p->certificate_type??'')==='cme'?'selected':'';?>>Có cấp tín chỉ CME</option><option value="noi-bo" <?php echo ($p->certificate_type??'noi-bo')==='noi-bo'?'selected':'';?>>Chứng nhận đào tạo nội bộ</option></select></div>
   <div class="col-md-4"><label class="form-label">Thứ tự hiển thị</label><input type="number" class="form-control" name="sort_order" value="<?php echo intval($p->sort_order??0);?>"></div>
   <div class="col-md-8"><label class="form-label">Tệp kế hoạch PDF <?php echo empty($p->attachment_path)?'<span class="text-danger">*</span>':'';?></label><input type="file" class="form-control" name="attachment" accept="application/pdf,.pdf" <?php echo empty($p->attachment_path)?'required':'';?>><small class="text-muted">Chỉ nhận PDF, dung lượng tối đa 20MB.</small><?php if(!empty($p->attachment_path)):?><div class="mt-2"><a target="_blank" href="<?php echo XC_URL.'/uploads/training-plans/'.rawurlencode($p->attachment_path);?>"><i class="fa-regular fa-file-pdf me-1"></i><?php echo trainingFormH($p->attachment_name);?></a></div><?php endif;?></div>
   <div class="col-md-4"><label class="form-label">Thông tin người gửi tệp</label><input class="form-control" name="attachment_sender" value="<?php echo trainingFormH($p->attachment_sender??'');?>" placeholder="Phòng KHTH - 07/10/2026 09:00"></div>
  </div></div></div>
  <div class="text-end mb-4"><a class="btn btn-light" href="<?php echo XC_URL;?>/admin/trainings">Hủy</a> <button class="btn btn-primary" id="save-training"><i class="fa-solid fa-floppy-disk me-1"></i>Lưu bản nháp</button></div>
 </form>
</div>
<script>$(function(){$('#training-plan-form').on('submit',function(e){e.preventDefault();var fd=new FormData(this),btn=$('#save-training').prop('disabled',true);$.ajax({url:'<?php echo XC_URL;?>/api/trainingPlanSave',type:'POST',data:fd,processData:false,contentType:false,dataType:'json'}).done(function(r){if(r.status==200){Swal.fire({icon:'success',title:r.message,timer:1000,showConfirmButton:false});setTimeout(function(){location.href=r.returnUrl},1050)}else Swal.fire('Không thể lưu',r.message,'error')}).fail(function(){Swal.fire('Lỗi','Không thể kết nối máy chủ.','error')}).always(function(){btn.prop('disabled',false)})})});</script>
<?php require 'footer.php';?>
