CREATE TABLE IF NOT EXISTS `hicrm_medical_campaigns` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campaign_code` VARCHAR(50) NOT NULL,
  `campaign_type` VARCHAR(30) NOT NULL COMMENT 'truyenthong or nhandao',
  `title` VARCHAR(500) NOT NULL,
  `summary` TEXT NULL,
  `content` LONGTEXT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `location` VARCHAR(500) NOT NULL,
  `organizer` VARCHAR(255) NULL,
  `target_audience` TEXT NULL,
  `image_name` VARCHAR(255) NULL,
  `image_path` VARCHAR(500) NULL,
  `attachment_name` VARCHAR(255) NULL,
  `attachment_path` VARCHAR(500) NULL,
  `attachment_type` VARCHAR(100) NULL,
  `attachment_size` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 draft, 2 pending, 3 approved, 4 published, 99 deleted',
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` DATETIME NULL,
  `submitted_by` INT NULL,
  `submitted_at` DATETIME NULL,
  `approved_by` INT NULL,
  `approved_at` DATETIME NULL,
  `published_by` INT NULL,
  `published_at` DATETIME NULL,
  `rejection_reason` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_medical_campaign_code` (`campaign_code`),
  KEY `idx_medical_campaign_public` (`status`, `campaign_type`, `start_date`, `sort_order`),
  KEY `idx_medical_campaign_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
