CREATE TABLE IF NOT EXISTS `hicrm_training_plans` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plan_code` VARCHAR(50) NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `summary` TEXT NULL,
  `priority_level` VARCHAR(20) NOT NULL DEFAULT 'normal',
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `organizer` VARCHAR(255) NOT NULL,
  `target_staff` TEXT NULL,
  `training_form` VARCHAR(30) NOT NULL DEFAULT 'tap-trung',
  `certificate_type` VARCHAR(30) NOT NULL DEFAULT 'noi-bo',
  `department_name` VARCHAR(255) NULL,
  `attachment_name` VARCHAR(255) NULL,
  `attachment_path` VARCHAR(500) NULL,
  `attachment_type` VARCHAR(100) NULL,
  `attachment_size` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `attachment_sender` VARCHAR(255) NULL,
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 draft, 2 pending, 3 approved, 4 published, 99 deleted',
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` DATETIME NULL,
  `submitted_by` INT NULL,
  `submitted_at` DATETIME NULL,
  `approved_by` INT NULL,
  `approved_at` DATETIME NULL,
  `published_by` INT NULL,
  `published_at` DATETIME NULL,
  `rejection_reason` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_training_plan_code` (`plan_code`),
  KEY `idx_training_plan_public` (`status`, `start_date`, `sort_order`),
  KEY `idx_training_plan_organizer` (`organizer`),
  KEY `idx_training_plan_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
